- lua/textcase/extensions/whichkey.lua
- lua/textcase/plugin/plugin.lua
- lua/textcase/plugin/presets.lua
This PR adds description to the keybindings
WhichKey
Telescope
TODO:
[ ] Sort which key mappings (Should create a different issue)
[ ] Show key mappings for partial keys, like `ga` and `gao` (Should create a different issue)
[ ] Clean up after finding out `vim.keymap.set('n', '<key>', lua_func, {desc = 'this is what I do'})` does almost all the job
> fixbug: Add description to keymaps

- .github/workflows/ci.yml
Actually... maybe a better solution could be to include nightly as @peterfication already did (and dismiss this PR), but not as a mandatory check.
I see it is possible to define which checks are required:
> Patch: Unit tests shouldn't run on Nightly Neovim

- .github/workflows/ci.yml
- .github/workflows/neovim-nightly.yml
- README.md
This PR adds status badges to the Readme. 
`All tests` will be always green (ideally) and it communicates the plugin has testing coverage (at some extent so far...)
`Neovim Nightly badge` is updated daily and will communicate when there is a breaking change in the near future
> Added tests for Neovim Nightly and Status Badges

- .github/workflows/ci.yml
- README.md
- lua/constants.lua
- tests/environments/minimal.lua
- tests/environments/telescope.lua
- tests/run.sh
- tests/textcase/lsp/lsp_spec.lua
- tests/textcase/plugin/plugin_spec.lua
- tests/textcase/telescope/telescope_spec.lua
It failed as expected for Neovim 9<
It must be safe to disable those tests temporarily. If this PR gets merged I'm going to add an issue to track adding tests for version 8 back
> Tests: Add Tests for Telescope, Quick Change in Normal Mode

- lua/textcase/plugin/plugin.lua
- tests/textcase/plugin/plugin_spec.lua
- tests/textcase/plugin/subs_spec.lua
This happens because to_lower_case and to_snake_case, as well as
to_upper_case and to_constant_case can yield the same result and hence a
word is replaced twice.
This only happens if the subs command adds a word, e.g.:
```
:Subs/lorem ipsum/lorem ipsum nunc/
```
>  Subs command which adds a word will add it twice sometimes

- tests/textcase/plugin/subs_spec.lua
Makes sure https://github.com/johmsalas/text-case.nvim/issues/36 does not happen again.
> Add test case for Subs/a/aa

- README.md
- lua/textcase/plugin/presets.lua
- tests/textcase/plugin/options/default_keymappings_false_spec.lua
- tests/textcase/plugin/options/prefix_spec.lua
This way, it's clear to the user how to use the plugin by just looking at the example setup scripts and the presentend default options.
It also allows for other possible options in the future.
This also adds tests for the options.
This PR partially addresses the problems of https://github.com/johmsalas/text-case.nvim/issues/45
> Adjust options for setup function

- README.md
- lua/textcase/init.lua
- lua/textcase/plugin/presets.lua
- tests/textcase/plugin/options/enabled_methods_spec.lua
This PR makes it possible to select the methods that should be registered for the default keymappings. It also prepares the possibility to add this method selection for Telescope.
Partially addresses https://github.com/johmsalas/text-case.nvim/issues/45
> Add option to select methods

- lua/textcase/plugin/plugin.lua
Since `methods_by_method_name` has been introduced, this field is no longer used or needed.
> Remove methods_by_desc from state

- .github/workflows/ci.yml
- README.md
Otherwise, a PR CI failure will lead to a broken badge.
> NOTE: The badge will only start to work when this PR is merged because the main branch has no CI runs yet. Hence, the added push event for CI.
> Use main branch for README badge

- Justfile
- lua/telescope/_extensions/textcase.lua
- tests/textcase/telescope/telescope_spec.lua
So that it's possible to run `:Telescope textcase`.
> Provide default picker in telescope extension

- .github/workflows/release-please.yml
https://github.com/googleapis/release-please
> Release Please automates CHANGELOG generation, the creation of GitHub releases, and version bumps for your projects.
> It does so by parsing your git history, looking for [Conventional Commit messages](https://www.conventionalcommits.org/), and creating release PRs.
> It does not handle publication to package managers or handle complex branch management.
> chore: release-please

- lua/textcase/plugin/conversion.lua
> chore: Upgrade from deprecated buf_request to buf_request_all for LSP

- lua/textcase/plugin/conversion.lua
- lua/textcase/shared/utils.lua
- tests/test_helpers.lua
- tests/textcase/lsp/fixtures/destructuring-bar-as-constant.ts
- tests/textcase/lsp/fixtures/destructuring-foo-as-constant.ts
- tests/textcase/lsp/fixtures/destructuring.ts
- tests/textcase/lsp/lsp_spec.lua
> feat: LSP rename converts next word if located in a non word character

- README.md
Lazyvim default mapping was only loaded after using Telescope.
This is a quick PR for mitigating the issue in the readme.
> fix: Correct documentation for LazyVim

- lua/textcase/plugin/plugin.lua
- tests/textcase/plugin/subs_spec.lua
Until now, it was only working properly for visual block mode. If visual
line had a short last line selected, it wouldn't work because in visual
block mode, this means that the range is as short as the last line.
So if the last line was a line with 0 chars, which can happen easily
in coding files, it would not work.
Example:
```typescript
const foo = "bar";
const bar = "bar";
console.log(foo);
````
In this example, selecting the first two lines and doing a `Subs` will
work as expected. However, if the third line is selected, nothing will
happen because the third line has 0 chars and hence the visual block
mode will have a range of 0 chars.
**This change fixes that.**
Fixes https://github.com/johmsalas/text-case.nvim/issues/117
> fix(Subs): distinguish visual block mode and visual line mode

- README.md
- lua/textcase/plugin/presets.lua
- tests/textcase/plugin/options/substitue_command_name_spec.lua
Fixes https://github.com/johmsalas/text-case.nvim/issues/129
NOTE: After this is merged, a refactor of the replace commands could make sense. Right now, the inner workings are still hard coded to the name `Subs`. And it registers the same methods for both commands in the plugin state.
> feat(Subs): adjustable name for substitude command

- lua/textcase/shared/utils.lua
- tests/textcase/plugin/commands/subs_spec.lua
> fix(subs): Avoid modifying a match that has already been altered.

- lua/textcase/conversions/stringcase.lua
We didn't know they existed before.
Fixes https://github.com/johmsalas/text-case.nvim/issues/152
> Use Vim toupper tolower

- README.md
The example would previously only register the Telescope command for lazy loading the entire plugin.
> fix(docs): Updates LazyVim example setup to lazy load on all default invocations

- README.md
- lua/textcase/extensions/whichkey.lua
- lua/textcase/plugin/plugin.lua
- lua/textcase/plugin/presets.lua
- tests/textcase/telescope/telescope_spec.lua
Hi! I noticed that this plugin uses `v` to create mappings. This is a common mistake. `v` creates the keymaps in both Visual _and_ Select mode. It makes sense to me to only create the keymaps in select mode. For this, `x` should be used instead. Here's `:help map-table`:
| Mode Command | Norm | Ins | Cmd | Vis | Sel | Opr | Term | Lang |
| ------------ | ---- | --- | --- | --- | --- | --- | ---- | ---- |
| ...          |      |     |     |     |     |     |      |      |
| `v[nore]map` | -    | -   | -   | yes | yes | -   | -    | -    |
| `x[nore]map` | -    | -   | -   | yes | -   | -   | -    | -    |
> Fix: create only visual mode mappings, not select mode mappings

- lua/textcase/extensions/whichkey.lua
- lua/textcase/plugin/presets.lua
Fixes #169
Also refactors the extension a little bit to hide the version-specific shape of the whichkey spec inside of `extensions/whichkey.lua`.
> fix: use whichkey.add instead of whichkey.register
